INCLUDES += -I$(RIOTBOARD)/common/stm32/include

PROGRAMMER ?= openocd

OPENOCD_DEBUG_ADAPTER ?= stlink
STLINK_VERSION ?= 3

ifeq (openocd,$(PROGRAMMER))
  PORT_LINUX ?= /dev/ttyUSB0
endif


include $(RIOTMAKE)/boards/stm32.inc.mk
